import mongoose from 'mongoose';
const userSchema = new mongoose.Schema(
  { avatarUrl: { default: "",
      type: String, },
    email: { index: true,
      lowercase: true,
      required: true,
      trim: true,
      type: String,
      unique: true, },
    emailVerificationExpiresAt: { default: null,
      type: Date, },
    emailVerificationToken: { default: null,
      index: true,
      type: String,
      unique: true, },
    fullName: { default: "New User",
      index: true,
      trim: true,
      type: String, },
    isVerified: { default: false,
      type: Boolean, },
    lastLoginAt: { default: null,
      index: true,
      type: Date, },
    password: { required: true,
      type: String, },
    resetPasswordExpiresAt: { default: null,
      type: Date, },
    resetPasswordToken: { default: null,
      index: true,
      type: String,
      unique: true, },
    timezone: { default: "UTC",
      type: String, }, },
  { timestamps: true,
    versionKey: false, },
);
export default mongoose.model("User", userSchema);
